### ISSUE TITLE
Quality Management Strategy

### ISSUE THREAD

**Issue by Polonalf** [isthatcentered/madera#11]

**Comment by Polonalf** [comment]
N’hésitez pas à modifier : la qualité je n'en ai jamais fait de cette façon :/

**Comment by isthatcentered** [comment]
Quality Management Strategy à relire par tout le monde et à valider avant jeudi
Commentaires de modification à faire dans le git

**Comment by isthatcentered** [comment]
A valider avec Pascal, mais de ce que je comprends dans ce doc on est sensé fournir le process step by step qui sera appliqué à chaque document (template a, review par x puis y, blah blah blah)

**Comment by Balador59** [comment]
Je trouve ça un peu light non ?
