### ISSUE TITLE
Modélisation UML - Cas d'utilisation module devis

### ISSUE THREAD

**Issue by isthatcentered** [isthatcentered/madera#17]

**Comment by Balador59** [comment]
Modélisation UML des cas d'utilisation des 3 Modules de Madera

J'ai généré un fichier PDF en vectoriel pour que vous puissiez regarder ça dans une bonne qualité 😄 

J'ai aussi fait un "Recueil fonctionnel" (copié collé xD) des différents modules, ça pourra servir pour le dév et pour les mockup, je vous l'ai partagé via [Dropbox Paper](https://paper.dropbox.com/doc/Recueil-fonctionnel-UML-cas-dutilisation-igE27mvHeG2KBlgqWoaCS)
J'ai récupérer les infos dans la doc Madera pages 15 - 16 -17 18

**Comment by isthatcentered** [comment]
Cas d'utilisation à relire par tout le monde et à valider avant jeudi
Commentaires de modification à faire dans le git

**Comment by isthatcentered** [comment]
Ok pour moi

**Comment by Polonalf** [comment]
Doit on gerer les stocks en tant qu'ingénieur ? Sinon 👍!!!
