### ISSUE TITLE
scrum kickoff

### ISSUE THREAD

**Issue by isthatcentered** [isthatcentered/madera#21]

**Comment by isthatcentered** [comment]
Review
modified: 
- kanban board url
- team values: 
   - Fiabilité du code (testing) 
   - Qualité du code (peer review) 
   - Montée en compétence (pair programming)
- Dod modifiée
- Dor modified, (was confused with DOD)
- removed "product vision" (was: "go look in the docs")

**Comment by Balador59** [comment]
👍

**Comment by Polonalf** [comment]
Mise en forme terminer.

**Comment by LordBaptiste** [comment]
👍

**Comment by isthatcentered** [comment]
A formater par Nicolas

**Comment by Balador59** [comment]
@All To Review
