### ISSUE TITLE
Création Template formatage 

### ISSUE THREAD

**Issue by Balador59** [isthatcentered/madera#23]
Création d'un template pour la mise en forme des fichiers Word

**Comment by Balador59** [comment]
Disponible dans la Dropbox dans Projet MADERA/Tools/
Dispo [ici](https://www.dropbox.com/s/lz92pqg8zsnoiw5/Template%20Doc%20Madera.docx?dl=0)
A copier pour ne pas écraser le template.
A review pour savoir si je doit rajouter des choses.

**Comment by LordBaptiste** [comment]
Dans le Brief project que t'avais formaté avant les titres 1 sont soulignés, mais je suppose que c'est plus d'actualité.
donc du coup 👍

**Comment by Balador59** [comment]
corrigé  :smirk:
