### ISSUE TITLE
Document - Initiation stage plan (project plan)

### ISSUE THREAD

**Issue by isthatcentered** [isthatcentered/madera#3]
The first plan you need to make in a PRINCE2 project is the Initiation Stage Plan.

Initiating a project takes time and money and should be planned and approved like any other work in the project. The Initiation Stage Plan is just like any other Stage Plan with the exception that (some of) the products to be produced are given – the Project Initiation Document and the Benefits Review Plan. 

https://www.dropbox.com/s/76cfenx8hrg1d0n/InitiationStagePlanTemplate.docx?dl=0

**Comment by isthatcentered** [comment]
Revu

**Comment by isthatcentered** [comment]
A relire par tout le monde

**Comment by isthatcentered** [comment]
Je suis pas sur qu'on soit bon dans ce doc, ça me parait pas très concret. Je le valide pour le moment, mais on a clairement interret à le relire avec Pascal

**Comment by Polonalf** [comment]
+1 avec Edouard

**Comment by Balador59** [comment]
👍

**Comment by isthatcentered** [comment]
A Relire par tout le monde
