### ISSUE TITLE
Document - Benefits Review Plan

### ISSUE THREAD

**Issue by isthatcentered** [isthatcentered/madera#4]
The PRINCE2 Benefits Review Plan defining how, when and by whom the benefits will be realized

A Benefits Review Plan is used to define how and when a measurement of the achievement of the project’s benefits, expected by the Senior user, can be made.

https://www.dropbox.com/s/13vc2z3jyki26bh/BenefitsReviewPlanTemplate.docx?dl=0

**Comment by Balador59** [comment]
👍

**Comment by Polonalf** [comment]
👍

**Comment by LordBaptiste** [comment]
ok pour moi

pour le point 3.2 je préciserai comment et quand on mesurerai ces bénéfices pour faire un peu plus factuel:

- Adoption de l'application: enquête de satisfaction lors des premiers mois d'usage
- Gestion des commandes: 
1. graph comparatif avant/après sur les temps de traitement des devis (duree moyenne de clôture d'un projet par exemple)
2. graph comparatif avant/après sur le nombre de pénalités dû à des retards de livraison (on peut imaginer)

- Gestion du stock:
1. graph comparatif avant/après sur les délais de commandes après l'acceptation d'un devis.
2. recueil du nombres d'alerte pour le stock qui ont permis d'éviter des ruptures de stock

**Comment by isthatcentered** [comment]
Intégration des commentaires

**Comment by isthatcentered** [comment]
Le formatage sera fait ensuite par Nicolas

**Comment by isthatcentered** [comment]
Modifications integrées, à formater.

**Comment by Polonalf** [comment]
👍
