### ISSUE TITLE
Document - Project brief

### ISSUE THREAD

**Issue by isthatcentered** [isthatcentered/madera#5]
Secure a good start for your PRINCE2 project by producing a quality Project Brief. 

The Project Brief is used to provide a full and firm foundation for the initiation of the project. It needs to be reviewed and approved by the Project Board, together with an Outline Business case and an Initiation Stage Plan, before a project it initiated.

https://www.dropbox.com/s/zyacrzoi6hoxihe/ProjectBriefTemplate.docx?dl=0

**Comment by isthatcentered** [comment]
This doc now needs to be reviewed and approved by everyone

**Comment by Balador59** [comment]
👍

**Comment by LordBaptiste** [comment]
commentaires et corrections

**Comment by Balador59** [comment]
New review needeed

**Comment by isthatcentered** [comment]
- Je supprimerais l'intro et mettrais la desc projet directement en 1. Elle n'apporte rien et vas juste nous permettre de nous faire déchiré (beh, z'ont pas signé les placeholder tabernacle ?)

- respect le formattage :o

- 3.resultats attendus:
Le projet sera clôturé par la remise au client de l’applicatif répondant aux recalcifications validées. Le but de ce projet est de fournir une application répondant aux besoins de nos commerciaux afin qu’ils puissent offrir la meilleure prestation possible en face du client.  Cette application doit être facile d’utilisation et encourager nos commerciaux à promouvoir les maisons modulaires.

en -> Lors de la cloture du projet, Madera doit avoir en main une application apportant les réponses technologiques aux besoins générés par l'atteinte des buts commerciaux spécifiés en II.2. Afin de garantir son adoption par l'ensemble des équipes, elle doit aussi répondre aux différents besoins des équipes l'utilisant et garantir la facilité pour l'équipe commercial de créer "sur le moment" un devis de maison modulire.

- Je mettrais l'equipe de management avant la methode projet, et finirais donc sur la methode en mentionnant que copain guy fera ici office de PO/sera notre principal retour sur l'avancement (ce qui est aussi un risque pour le projet en soit si c'est pas le boss des boss des meilleurs chefs).

**Comment by Polonalf** [comment]
Quid du businees plan Outline ? 
D'accord avec les commentaires d'Edouard.

**Comment by LordBaptiste** [comment]
je pense qu'on peut zapper le business plan outline.
ok aussi avec les modifs proposées par Edouard

j'avais mis des com sur la partie 2.2 dans dropbox paper : https://paper.dropbox.com/doc/Project-Brief-Madera-tESPHHWOeju3VMeHYHCXY

à savoir au niveau des Critères d’acceptations qu'est ce qu'on peut définir ? J’ai pas assez d’expérience la dedans pour détailler plus. A partir de quand une fonctionnalité est validée en agile ? est ce qu’on prévoit une recette usine ?

**Comment by isthatcentered** [comment]
A formater par Baptiste
