### ISSUE TITLE
Adding project management files to git for versioning?

### ISSUE THREAD

**Issue by isthatcentered** [isthatcentered/madera#7]
Wouldn't that be nicer than dropbow? free versioning?

**Comment by Balador59** [comment]
why not, ohh fuck, in french it's good too ?

Pourquoi pas, par-contre, github reconnait-il les formats docx ? ou va t'on ce retrouver avec un fichier hashé ?

La dessus il faut commit à chaque modification avec un message (je sens les oublis arriver).
Et aprés faut pull le repo à chaque fois pour vérif les nouvelles modifs.

Donc sur le principe oui, fonctionnellement parlant, ça va nous mettre en galère je pense.
