### ISSUE TITLE
Risk Management Strategy

### ISSUE THREAD

**Issue by Polonalf** [isthatcentered/madera#8]

**Comment by Balador59** [comment]
👍

**Comment by isthatcentered** [comment]
- j'ai dégagé l'intro projet madéra sert à machin, c'est bon tout le monde l'a assez vue je pense et c'est pas le but de ce doc. Je l'ai remplacée par une intro sur la gestion des risques

- Attention aux descriptions (erreur de casting, le serveur meurt, techno mal choisie, ...) ça sonne pas top
- "Chaque risque à une fiche de risque qui lui est propre et référencé dansun dossier spécifique." Oulah non on a pas ça nous nan?
- réorganisation des titres sous titres et simplification
- reupload en Risk-Management-Strategy-25-08.docx

**Comment by Polonalf** [comment]
Modification des descriptions.
Je suis sur les fiches actuellement, si le tableau suffit pour vous je ne m'y attarde pas.

**Comment by isthatcentered** [comment]
A formatter celon le style du project brief

**Comment by LordBaptiste** [comment]
Il faudrait ajouter un ptit mot sur les rôles et responsabilités
mais sinon 👍
